### ISSUE TITLE
bug: handleClick not function 

### ISSUE THREAD

**Issue by ihtml5** [react-love/react-next#4]
**problem**: handleClick not function 
**file**:  https://github.com/react-love/react-next/blob/master/components/Home/index.js
![image](https://user-images.githubusercontent.com/6822604/46719695-2b1e3100-cca1-11e8-9e35-d2f305af399c.png)

**Comment by hyy1115** [comment]
handleClick已经删掉了，你可以自定义handleClick

**Comment by ihtml5** [comment]
ok
