### ISSUE TITLE
请教 next.js 做 seo 优化的原理

### ISSUE THREAD

**Issue by NicholasNC** [react-love/react-next#5]
您好，最近想用 react 提升门户网站的开发效率（但，最蛋疼的是要做 seo 优化）

网上比较好的答案都指向了 next.js

想请教一下 next.js 可以实现 seo 优化的原理 O(∩_∩)O

以下内容纯碎瞎猜，还没验证，请大神指点指点

next.js出来的效果是否跟传统多页面的网站一样？——每一个页面对应一个路由，然后在访问每一个路由时向服务器发送一个请求，返回当前路由对应的页面的数据。（ ps：在下孤落寡闻，目前只知道这种形式对 seo 友好——相当于不需要让爬虫执行 js，所有页面的数据都从服务器返回）

**Comment by hyy1115** [comment]
首次加载是服务端渲染当前路由的页面，然后加载其他路由的js，转回客户端渲染。
